# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  encoding: utf8
  database: apartment_development
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: apartment_test
  pool: 5

production:
  adapter: pg
  encoding: utf8
  database: pg_production
  pool: 5
  timeout: 5000

